# Generated by Django 3.2.16 on 2023-01-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230104_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_class',
            name='trainers',
            field=models.CharField(choices=[('Karol', 'Karol')], default='Karol', max_length=10),
        ),
    ]
