# Generated by Django 3.2.16 on 2023-01-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_class_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_class',
            name='requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_class',
            name='trainers',
            field=models.CharField(choices=[('Karol', 'Karol'), ('John', 'John'), ('Sara', 'Sara'), ('Ivan', 'Ivan')], default='Karol', max_length=10),
        ),
    ]
