# Generated by Django 3.2.16 on 2023-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230112_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_class',
            name='trainers',
            field=models.CharField(choices=[('Karol', 'Karol'), ('admin123', 'admin123'), ('John', 'John'), ('Sara', 'Sara'), ('Ivan', 'Ivan')], default='Karol', max_length=10),
        ),
    ]
